name: pag_flutter
description: "A Flutter plugin for PAG(Portable Animated Graphics) files that renders After Effects animations natively across multiple platforms."
version: 0.1.1
publish_to: none

topics:
  - libpag
  - pag

environment:
  sdk: ^3.6.0
  flutter: ">=3.7.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  pag_platform_interface:
    path: ../pag_platform_interface
  pag_android:
    path: ../pag_android
  pag_darwin:
    path: ../pag_darwin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: pag_android
      ios:
        default_package: pag_darwin
